CREATE DATABASE `Artists_treasure`;
USE `Artists_treasure`;

CREATE TABLE `ARTWORK` (
	`AK_ID` INT NOT NULL PRIMARY KEY,
    `AK_DATE` DATE NOT NULL,
    `AK_NAME` VARCHAR(255) NOT NULL,
    `AK_MATERIAL` VARCHAR(255),
    `AK_SIZE` DECIMAL(6,1),
    `AK_SIGNATURE_Y` DATE NOT NULL,
    `AK_SIGNATURE_M` DATE,
    `AK_THEME` INT,
    `AK_INTRODUCE` TEXT,
    `AK_TIMES` INT,
    `AK_RACETIMES` INT,
    `AK_LOCATION` INT NOT NULL,
    `AK_MEDIA` INT,
    `AK_STATE` BOOL NOT NULL,
    `AK_REMARK` TEXT
);
DESCRIBE `ARTWORK`;
#DROP DATABASE `ARTWORK`

CREATE TABLE `COLLECTION` (
	`COL_ID` INT NOT NULL PRIMARY KEY,
    `COL_DATE` DATE NOT NULL,
    `COL_ARTIST` VARCHAR(255),
    `COL_NAME` VARCHAR(255),
    `COL_MATERIAL` VARCHAR(255),
    `COL_SIZE` DECIMAL(6,1) NOT NULL,
    `COL_SIGNATURE_Y` YEAR NOT NULL,
    `COL_SIGNATURE_Y` YEAR NOT NULL,
);
DESCRIBE `COLLECTION`;
DROP DATABASE `COLLECTION`