CREATE DATABASE `Artists_treasure`;
USE `Artists_treasure`;
#DROP DATABASE `Artists_treasure`;
#SHOW DATABASES;
CREATE TABLE `ARTWORK` (
	`AK_ID` VARCHAR(7) NOT NULL PRIMARY KEY,
    `AK_DATE` DATE NOT NULL,
    `AK_NAME` VARCHAR(255) NOT NULL,
    `AK_MATERIAL` VARCHAR(255),
    `AK_SIZE` DECIMAL(6,1),
    `AK_SIGNATURE_Y` DECIMAL(4,0) NOT NULL,
    `AK_SIGNATURE_M` DECIMAL(2,0),
    `AK_THEME` VARCHAR(30) UNIQUE,
    `AK_INTRODUCE` TEXT,
    `AK_TIMES` INT,
    `AK_RACETIMES` INT,
    `AK_LOCATION` VARCHAR(30) NOT NULL,
    `AK_MEDIA` VARCHAR(255),
    `AK_STATE` BOOL NOT NULL,
    `AK_REMARK` TEXT,
    CHECK(`AK_SIGNATURE_Y` BETWEEN 0000 AND 2100),
    CHECK(`AK_SIGNATURE_M` BETWEEN 1 AND 12)
);
#DESCRIBE `ARTWORK`;
#DROP TABLE `ARTWORK`;

CREATE TABLE `COLLECTION` (
	`COL_ID` VARCHAR(8) NOT NULL PRIMARY KEY,
    `COL_DATE` DATE NOT NULL,
    `COL_ARTIST` VARCHAR(255),
    `COL_NAME` VARCHAR(255),
    `COL_MATERIAL` VARCHAR(255),
    `COL_SIZE` DECIMAL(6,1) NOT NULL,
    `COL_SIGNATURE_Y` YEAR NOT NULL,
    `COL_SIGNATURE_M` TINYINT NOT NULL,
    `COL_THEME` INT,
    `COL_GET_DATE` DATE NOT NULL,
    `COL_DPRICE` INT,
    `COL_INTRODUCE` TEXT,
    `COL_TIMES` INT,
    `COL_LOCATION` TEXT NOT NULL,
    `COL_MEDIA` VARCHAR(255),
    `COL_STATE` BOOL NOT NULL,
    `COL_REMARK` TEXT,
    CHECK(`COL_SIGNATURE_Y` BETWEEN 0000 AND 2100),
    CHECK(`COL_SIGNATURE_M` BETWEEN 1 AND 12)
);
#DESCRIBE `COLLECTION`;
#DROP TABLE `COLLECTION`;

CREATE TABLE `THEME`(
	`TE_ID` VARCHAR(7) NOT NULL PRIMARY KEY,
    `AK_THEME` VARCHAR(30) NOT NULL,
	FOREIGN KEY (AK_THEME) REFERENCES ARTWORK(AK_THEME)
);


CREATE TABLE `PLACE`(
	`PE_ID` VARCHAR(7) NOT NULL PRIMARY KEY,
    `PE_NAME` VARCHAR(30) NOT NULL
);
#DESCRIBE `THEME`;



CREATE TABLE `TRADE`(
	`TDE_ID` VARCHAR(8) NOT NULL PRIMARY KEY,
    `TDE_PLACE` VARCHAR(255) NOT NULL,
    `TDE_DATE` DATE NOT NULL,
	`TDE_BUYER` VARCHAR(100) NOT NULL,
	`TDE_SELLER` VARCHAR(100) NOT NULL,
	`TDE_TOTAL_ITEM` INT NOT NULL,
	`TDE_TOTAL_PRICE` INT NOT NULL,
	`TDE_REMARK`TEXT
);
#DESCRIBE `TRADE`;

CREATE TABLE `TRADEDETAIL`(
	`TDED_ID` VARCHAR(9) NOT NULL PRIMARY KEY,
	`TDE_ID` VARCHAR(8) NOT NULL,
	`AK_ID` VARCHAR(7) NOT NULL,
	`COL_ID` VARCHAR(8) NOT NULL,
	`TDED_PRICE` INT NOT NULL,
	`TDED_REMARK` TEXT,
	FOREIGN KEY (TDE_ID) REFERENCES TRADE(TDE_ID), 
    FOREIGN KEY (AK_ID) REFERENCES ARTWORK(AK_ID),
    FOREIGN KEY (COL_ID) REFERENCES COLLECTION(COL_ID)
);
#DESCRIBE `TRADEDETAIL`;


CREATE TABLE `EXHIBITION`(
	`EN_ID` VARCHAR(7) NOT NULL PRIMARY KEY,
	`EN_LOCATION` VARCHAR(255) NOT NULL,
	`EN_ORGANIZER` VARCHAR(255) NOT NULL,
	`EN_NAME` VARCHAR(255) NOT NULL,
	`EN_START` DATE NOT NULL,
	`EN_FINISH` DATE NOT NULL,
	`EN_ITEM` INT NOT NULL,
	`EN_INTRODUCE` TEXT,
	`EN_REMARK` TEXT
);


CREATE TABLE `EXHIBITIONDETAIL`(
	`END_ID` VARCHAR(8) NOT NULL,
	`EN_ID` VARCHAR(7) NOT NULL,
	`AK_ID` VARCHAR(7),
	`COL_ID` VARCHAR(8), 
	`END_NAME` VARCHAR(255),
    FOREIGN KEY (EN_ID) REFERENCES EXHIBITION(EN_ID),
    FOREIGN KEY (AK_ID) REFERENCES ARTWORK(AK_ID),
    FOREIGN KEY (COL_ID) REFERENCES COLLECTION(COL_ID),
	CHECK((AK_ID IS NOT NULL AND COL_ID IS NULL) OR (AK_ID IS NULL AND COL_ID IS NOT NULL))
);


CREATE TABLE `CONTEST`(
	`CT_ID` VARCHAR(7) NOT NULL PRIMARY KEY,
	`CT_LOCATION` VARCHAR(255) NOT NULL,
	`CT_ORGANIZER` VARCHAR(255) NOT NULL,
	`CT_NAME` VARCHAR(255) NOT NULL,
	`CT_START` DATE NOT NULL,
	`CT_END` DATE NOT NULL,
	`CT_ITEM` INT NOT NULL,
	`CT_INTRODUCE` TEXT NOT NULL,
	`CT_REMARK` TEXT NOT NULL
);


CREATE TABLE `CONTESTDETAIL`(
	`CTD_ID` VARCHAR(8) NOT NULL,
	`CT_ID` VARCHAR(7) NOT NULL,
	`AK_ID` VARCHAR(7) NOT NULL,
	`CTD_NAME` VARCHAR(255),
	`CTD_RANK` INT NOT NULL,
	`CTD_AMOUNT` INT NOT NULL
);

#----------------------------------------------------------------------------------------------------
#輔助表
#FOR AK_ID FROM ARTWORK
CREATE TABLE IF NOT EXISTS AK_SEQUENCE (
    SEQ INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (SEQ)
);

#FOR COL_ID FROM COLLECTION
CREATE TABLE IF NOT EXISTS COL_SEQUENCE (
    SEQ INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (SEQ)
);

#FOR TE_ID FROM THEME
CREATE TABLE IF NOT EXISTS TE_SEQUENCE (
    SEQ INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (SEQ)
);

#FOR PE_ID FROM PLACE
CREATE TABLE IF NOT EXISTS PE_SEQUENCE (
    SEQ INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (SEQ)
);

#FOR TDE_ID FROM TRADE
CREATE TABLE IF NOT EXISTS TDE_SEQUENCE (
    SEQ INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (SEQ)
);

#FOR TDED_ID FROM TRADEDETAIL
CREATE TABLE IF NOT EXISTS TDED_SEQUENCE (
    SEQ INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (SEQ)
);

#FOR EN_ID FROM EXHIBITION
CREATE TABLE IF NOT EXISTS EN_SEQUENCE (
    SEQ INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (SEQ)
);

#FOR END_ID FROM EXHIBITIONDETAIL
CREATE TABLE IF NOT EXISTS END_SEQUENCE (
    SEQ INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (SEQ)
);

#FOR CT_ID FROM CONTEST
CREATE TABLE IF NOT EXISTS CT_SEQUENCE (
    SEQ INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (SEQ)
);

#FOR CTD_ID FROM CONTESTDETAIL
CREATE TABLE IF NOT EXISTS CTD_SEQUENCE (
    SEQ INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (SEQ)
);

#觸發器
DELIMITER //
#FOR AK_ID FROM ARTWORK
CREATE TRIGGER BEFORE_INSERT_AK_ID
BEFORE INSERT ON ARTWORK
FOR EACH ROW
BEGIN
    DECLARE NEW_ID VARCHAR(7);
    INSERT INTO AK_SEQUENCE VALUES (NULL);
    SET NEW_ID = CONCAT('AK', LPAD(LAST_INSERT_ID(), 5, '0'));
    SET NEW.AK_ID = NEW_ID;
END //

#FOR COL_ID FROM COLLECTION
CREATE TRIGGER BEFORE_INSERT_COL_ID
BEFORE INSERT ON COLLECTION
FOR EACH ROW
BEGIN
    DECLARE NEW_ID VARCHAR(8);
    INSERT INTO COL_SEQUENCE VALUES (NULL);
    SET NEW_ID = CONCAT('COL', LPAD(LAST_INSERT_ID(), 5, '0'));
    SET NEW.COL_ID = NEW_ID;
END //

#FOR TE_ID FROM THEME
CREATE TRIGGER BEFORE_INSERT_TE_ID
BEFORE INSERT ON THEME
FOR EACH ROW
BEGIN
    DECLARE NEW_ID VARCHAR(7);
    INSERT INTO TE_SEQUENCE VALUES (NULL);
    SET NEW_ID = CONCAT('TE', LPAD(LAST_INSERT_ID(), 5, '0'));
    SET NEW.TE_ID = NEW_ID;
END //

#FOR PE_ID FROM PLACE
CREATE TRIGGER BEFORE_INSERT_PE_ID
BEFORE INSERT ON PLACE
FOR EACH ROW
BEGIN
    DECLARE NEW_ID VARCHAR(7);
    INSERT INTO PE_SEQUENCE VALUES (NULL);
    SET NEW_ID = CONCAT('PE', LPAD(LAST_INSERT_ID(), 5, '0'));
    SET NEW.PE_ID = NEW_ID;
END //

#FOR TDE_ID FROM TRADE
CREATE TRIGGER BEFORE_INSERT_TDE_ID
BEFORE INSERT ON TRADE
FOR EACH ROW
BEGIN
    DECLARE NEW_ID VARCHAR(8);
    INSERT INTO TDE_SEQUENCE VALUES (NULL);
    SET NEW_ID = CONCAT('TDE', LPAD(LAST_INSERT_ID(), 5, '0'));
    SET NEW.TDE_ID = NEW_ID;
END //

#FOR TDED_ID FROM TRADEDETAIL
CREATE TRIGGER BEFORE_INSERT_TDED_ID
BEFORE INSERT ON TRADEDETAIL
FOR EACH ROW
BEGIN
    DECLARE NEW_ID VARCHAR(9);
    INSERT INTO TDED_SEQUENCE VALUES (NULL);
    SET NEW_ID = CONCAT('TDED', LPAD(LAST_INSERT_ID(), 5, '0'));
    SET NEW.TDED_ID = NEW_ID;
END //

#FOR EN_ID FROM EXHIBITION
CREATE TRIGGER BEFORE_INSERT_EN_ID
BEFORE INSERT ON EXHIBITION
FOR EACH ROW
BEGIN
    DECLARE NEW_ID VARCHAR(7);
    INSERT INTO EN_SEQUENCE VALUES (NULL);
    SET NEW_ID = CONCAT('EN', LPAD(LAST_INSERT_ID(), 5, '0'));
    SET NEW.EN_ID = NEW_ID;
END //

#FOR END_ID FROM EXHIBITIONDETAIL
CREATE TRIGGER BEFORE_INSERT_END_ID
BEFORE INSERT ON EXHIBITIONDETAIL
FOR EACH ROW
BEGIN
    DECLARE NEW_ID VARCHAR(8);
    INSERT INTO END_SEQUENCE VALUES (NULL);
    SET NEW_ID = CONCAT('END', LPAD(LAST_INSERT_ID(), 5, '0'));
    SET NEW.END_ID = NEW_ID;
END //

#FOR CT_ID FROM CONTEST
CREATE TRIGGER BEFORE_INSERT_CT_ID
BEFORE INSERT ON CONTEST
FOR EACH ROW
BEGIN
    DECLARE NEW_ID VARCHAR(7);
    INSERT INTO CT_SEQUENCE VALUES (NULL);
    SET NEW_ID = CONCAT('CT', LPAD(LAST_INSERT_ID(), 5, '0'));
    SET NEW.CT_ID = NEW_ID;
END //

#FOR CTD_ID FROM CONTESTDETAIL
CREATE TRIGGER BEFORE_INSERT_CTD_ID
BEFORE INSERT ON CONTESTDETAIL
FOR EACH ROW
BEGIN
    DECLARE NEW_ID VARCHAR(8);
    INSERT INTO CTD_SEQUENCE VALUES (NULL);
    SET NEW_ID = CONCAT('CTD', LPAD(LAST_INSERT_ID(), 5, '0'));
    SET NEW.CTD_ID = NEW_ID;
END //

DELIMITER ;
SHOW TABLES;
#DROP DATABASE ARTISTS_TREASURE;