CREATE DATABASE `Artists_treasure`;
USE `Artists_treasure`;
#DROP DATABASE `Artists_treasure`;
#SHOW DATABASES;
CREATE TABLE `ARTWORK` (
	`AK_ID` INT NOT NULL PRIMARY KEY,
    `AK_DATE` DATE NOT NULL,
    `AK_NAME` VARCHAR(255) NOT NULL,
    `AK_MATERIAL` VARCHAR(255),
    `AK_SIZE` DECIMAL(6,1),
    `AK_SIGNATURE_Y` DATE NOT NULL,
    `AK_SIGNATURE_M` DATE,
    `AK_THEME` INT,
    `AK_INTRODUCE` TEXT,
    `AK_TIMES` INT,
    `AK_RACETIMES` INT,
    `AK_LOCATION` INT NOT NULL,
    `AK_MEDIA` INT,
    `AK_STATE` BOOL NOT NULL,
    `AK_REMARK` TEXT
);
#DESCRIBE `ARTWORK`;
#DROP TABLE `ARTWORK`

CREATE TABLE `COLLECTION` (
	`COL_ID` INT NOT NULL PRIMARY KEY,
    `COL_DATE` DATE NOT NULL,
    `COL_ARTIST` VARCHAR(255),
    `COL_NAME` VARCHAR(255),
    `COL_MATERIAL` VARCHAR(255),
    `COL_SIZE` DECIMAL(6,1) NOT NULL,
    `COL_SIGNATURE_Y` YEAR NOT NULL,
    `COL_SIGNATURE_M` TINYINT NOT NULL,
    `COL_THEME` INT,
    `COL_GET_DATE` DATE NOT NULL,
    `COL_DPRICE` INT,
    `COL_INTRODUCE` TEXT,
    `COL_TIMES` INT,
    `COL_LOCATION` TEXT NOT NULL,
    `COL_MEDIA` VARCHAR(255),
    `COL_STATE` BOOL NOT NULL,
    `COL_REMARK` TEXT,
    CHECK(`COL_SIGNATURE_Y` BETWEEN 1 AND 12)
);
#DESCRIBE `COLLECTION`;
#DROP TABLE `COLLECTION`;

CREATE TABLE `THEME`(
	`TE_ID` INT NOT NULL PRIMARY KEY,
    `TE_NAME` VARCHAR(30) NOT NULL
);


CREATE TABLE `PLACE`(
	`PE_ID` INT NOT NULL PRIMARY KEY,
    `PE_NAME` VARCHAR(30) NOT NULL
);
#DESCRIBE `THEME`;



CREATE TABLE `TRADE`(
	`TDE_ID` INT NOT NULL PRIMARY KEY,
    `TDE_PLACE` VARCHAR(255) NOT NULL,
    `TDE_DATE` DATE NOT NULL,
	`TDE_BUYER` VARCHAR(100) NOT NULL,
	`TDE_SELLER`VARCHAR(100) NOT NULL,
	`TDE_TOTAL_ITEM` INT NOT NULL,
	`TDE_TOTAL_PRICE`INT NOT NULL,
	`TDE_REMARK`TEXT
);
#DESCRIBE `TRADE`;

CREATE TABLE `TRADEDETAIL`(
	`TDED_ID` INT NOT NULL PRIMARY KEY,
	`TDE_ID` INT NOT NULL,
	`AK_ID` INT NOT NULL,
	`COL_ID` INT NOT NULL,
	`TDED_PRICE` INT NOT NULL,
	`TDED_REMARK` TEXT,
	FOREIGN KEY (TDE_ID) REFERENCES TRADE(TDE_ID), 
    FOREIGN KEY (AK_ID) REFERENCES ARTWORK(AK_ID),
    FOREIGN KEY (COL_ID) REFERENCES COLLECTION(COL_ID)
);
#DESCRIBE `TRADEDETAIL`;


CREATE TABLE `EXHIBITION`(
	`EN_ID` INT NOT NULL PRIMARY KEY,
	`EN_LOCATION` VARCHAR(255) NOT NULL,
	`EN_ORGANIZER` VARCHAR(255) NOT NULL,
	`EN_NAME` VARCHAR(255) NOT NULL,
	`EN_START` DATE NOT NULL,
	`EN_FINISH` DATE NOT NULL,
	`EN_ITEM` INT NOT NULL,
	`EN_INTRODUCE` TEXT,
	`EN_REMARK` TEXT
);


CREATE TABLE `EXHIBITIONDETAIL`(
	`END_ID` INT NOT NULL,
	`EN_ID` INT NOT NULL,
	`AK_ID` INT,
	`COL_ID` INT, 
	`END_NAME` VARCHAR(255),
    FOREIGN KEY (EN_ID) REFERENCES EXHIBITION(EN_ID),
    FOREIGN KEY (AK_ID) REFERENCES ARTWORK(AK_ID),
    FOREIGN KEY (COL_ID) REFERENCES COLLECTION(COL_ID),
	CHECK((AK_ID IS NOT NULL AND COL_ID IS NULL) OR (AK_ID IS NULL AND COL_ID IS NOT NULL))
);


CREATE TABLE `CONTEST`(
	`CT_ID` INT NOT NULL PRIMARY KEY,
	`CT_LOCATION` VARCHAR(255) NOT NULL,
	`CT_ORGANIZER` VARCHAR(255) NOT NULL,
	`CT_NAME` VARCHAR(255) NOT NULL,
	`CT_START` DATE NOT NULL,
	`CT_END` DATE NOT NULL,
	`CT_ITEM` INT NOT NULL,
	`CT_INTRODUCE` TEXT NOT NULL,
	`CT_REMARK` TEXT NOT NULL
);


CREATE TABLE `CONTESTDETAIL`(
	`CTD_ID` INT NOT NULL,
	`CT_ID` INT NOT NULL,
	`AK_ID` INT NOT NULL,
	`CTD_NAME` VARCHAR(255),
	`CTD_RANK` INT NOT NULL,
	`CTD_AMOUNT` INT NOT NULL
);


#SHOW TABLES;