#輔助表
#FOR AK_ID FROM ARTWORK
CREATE TABLE IF NOT EXISTS AK_SEQUENCE (
    SEQ INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (SEQ)
);

#FOR COL_ID FROM COLLECTION
CREATE TABLE IF NOT EXISTS COL_SEQUENCE (
    SEQ INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (SEQ)
);

#FOR TE_ID FROM THEME
CREATE TABLE IF NOT EXISTS TE_SEQUENCE (
    SEQ INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (SEQ)
);

#FOR PE_ID FROM PLACE
CREATE TABLE IF NOT EXISTS PE_SEQUENCE (
    SEQ INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (SEQ)
);

#FOR TDE_ID FROM TRADE
CREATE TABLE IF NOT EXISTS TDE_SEQUENCE (
    SEQ INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (SEQ)
);

#FOR TDED_ID FROM TRADEDETAIL
CREATE TABLE IF NOT EXISTS TDED_SEQUENCE (
    SEQ INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (SEQ)
);

#FOR EN_ID FROM EXHIBITION
CREATE TABLE IF NOT EXISTS EN_SEQUENCE (
    SEQ INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (SEQ)
);

#FOR END_ID FROM EXHIBITIONDETAIL
CREATE TABLE IF NOT EXISTS END_SEQUENCE (
    SEQ INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (SEQ)
);

#FOR CT_ID FROM CONTEST
CREATE TABLE IF NOT EXISTS CT_SEQUENCE (
    SEQ INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (SEQ)
);

#FOR CTD_ID FROM CONTESTDETAIL
CREATE TABLE IF NOT EXISTS CTD_SEQUENCE (
    SEQ INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (SEQ)
);

#觸發器
DELIMITER //
#FOR AK_ID FROM ARTWORK
CREATE TRIGGER BEFORE_INSERT_AK_ID
BEFORE INSERT ON ARTWORK
FOR EACH ROW
BEGIN
    DECLARE NEW_ID VARCHAR(7);
    INSERT INTO AK_SEQUENCE VALUES (NULL);
    SET NEW_ID = CONCAT('AK', LPAD(LAST_INSERT_ID(), 5, '0'));
    SET NEW.AK_ID = NEW_ID;
END //

#FOR COL_ID FROM COLLECTION
CREATE TRIGGER BEFORE_INSERT_COL_ID
BEFORE INSERT ON COLLECTION
FOR EACH ROW
BEGIN
    DECLARE NEW_ID VARCHAR(8);
    INSERT INTO COL_SEQUENCE VALUES (NULL);
    SET NEW_ID = CONCAT('COL', LPAD(LAST_INSERT_ID(), 5, '0'));
    SET NEW.COL_ID = NEW_ID;
END //

#FOR TE_ID FROM THEME
CREATE TRIGGER BEFORE_INSERT_TE_ID
BEFORE INSERT ON THEME
FOR EACH ROW
BEGIN
    DECLARE NEW_ID VARCHAR(7);
    INSERT INTO TE_SEQUENCE VALUES (NULL);
    SET NEW_ID = CONCAT('TE', LPAD(LAST_INSERT_ID(), 5, '0'));
    SET NEW.TE_ID = NEW_ID;
END //

#FOR PE_ID FROM PLACE
CREATE TRIGGER BEFORE_INSERT_PE_ID
BEFORE INSERT ON PLACE
FOR EACH ROW
BEGIN
    DECLARE NEW_ID VARCHAR(7);
    INSERT INTO PE_SEQUENCE VALUES (NULL);
    SET NEW_ID = CONCAT('PE', LPAD(LAST_INSERT_ID(), 5, '0'));
    SET NEW.PE_ID = NEW_ID;
END //

#FOR TDE_ID FROM TRADE
CREATE TRIGGER BEFORE_INSERT_TDE_ID
BEFORE INSERT ON TRADE
FOR EACH ROW
BEGIN
    DECLARE NEW_ID VARCHAR(8);
    INSERT INTO TDE_SEQUENCE VALUES (NULL);
    SET NEW_ID = CONCAT('TDE', LPAD(LAST_INSERT_ID(), 5, '0'));
    SET NEW.TDE_ID = NEW_ID;
END //

#FOR TDED_ID FROM TRADEDETAIL
CREATE TRIGGER BEFORE_INSERT_TDED_ID
BEFORE INSERT ON TRADEDETAIL
FOR EACH ROW
BEGIN
    DECLARE NEW_ID VARCHAR(9);
    INSERT INTO TDED_SEQUENCE VALUES (NULL);
    SET NEW_ID = CONCAT('TDED', LPAD(LAST_INSERT_ID(), 5, '0'));
    SET NEW.TDED_ID = NEW_ID;
END //

#FOR EN_ID FROM EXHIBITION
CREATE TRIGGER BEFORE_INSERT_EN_ID
BEFORE INSERT ON EXHIBITION
FOR EACH ROW
BEGIN
    DECLARE NEW_ID VARCHAR(7);
    INSERT INTO EN_SEQUENCE VALUES (NULL);
    SET NEW_ID = CONCAT('EN', LPAD(LAST_INSERT_ID(), 5, '0'));
    SET NEW.EN_ID = NEW_ID;
END //

#FOR END_ID FROM EXHIBITIONDETAIL
CREATE TRIGGER BEFORE_INSERT_END_ID
BEFORE INSERT ON EXHIBITIONDETAIL
FOR EACH ROW
BEGIN
    DECLARE NEW_ID VARCHAR(8);
    INSERT INTO END_SEQUENCE VALUES (NULL);
    SET NEW_ID = CONCAT('END', LPAD(LAST_INSERT_ID(), 5, '0'));
    SET NEW.END_ID = NEW_ID;
END //

#FOR CT_ID FROM CONTEST
CREATE TRIGGER BEFORE_INSERT_CT_ID
BEFORE INSERT ON CONTEST
FOR EACH ROW
BEGIN
    DECLARE NEW_ID VARCHAR(7);
    INSERT INTO CT_SEQUENCE VALUES (NULL);
    SET NEW_ID = CONCAT('CT', LPAD(LAST_INSERT_ID(), 5, '0'));
    SET NEW.CT_ID = NEW_ID;
END //

#FOR CTD_ID FROM CONTESTDETAIL
CREATE TRIGGER BEFORE_INSERT_CTD_ID
BEFORE INSERT ON CONTESTDETAIL
FOR EACH ROW
BEGIN
    DECLARE NEW_ID VARCHAR(8);
    INSERT INTO CTD_SEQUENCE VALUES (NULL);
    SET NEW_ID = CONCAT('CTD', LPAD(LAST_INSERT_ID(), 5, '0'));
    SET NEW.CTD_ID = NEW_ID;
END //

DELIMITER ;