-- MySQL Script generated by MySQL Workbench
-- Thu Sep 26 11:25:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Artists_treasure
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Artists_treasure
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Artists_treasure` ;
-- -----------------------------------------------------
-- Schema Auto_increment
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Auto_increment
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Auto_increment` ;
USE `Artists_treasure` ;

-- -----------------------------------------------------
-- Table `Artists_treasure`.`ARTWORK`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Artists_treasure`.`ARTWORK` ;

CREATE TABLE IF NOT EXISTS `Artists_treasure`.`ARTWORK` (
  `AK_ID` VARCHAR(7) NOT NULL,
  `AK_DATE` DATE NOT NULL,
  `AK_NAME` VARCHAR(255) NOT NULL,
  `AK_MATERIAL` VARCHAR(255) NULL DEFAULT NULL,
  `AK_SIZE` DECIMAL(6,1) NULL DEFAULT NULL,
  `AK_SIGNATURE_Y` DATE NOT NULL,
  `AK_SIGNATURE_M` DATE NULL DEFAULT NULL,
  `AK_THEME` INT NULL DEFAULT NULL,
  `AK_INTRODUCE` TEXT NULL DEFAULT NULL,
  `AK_TIMES` INT NULL DEFAULT NULL,
  `AK_RACETIMES` INT NULL DEFAULT NULL,
  `AK_LOCATION` INT NOT NULL,
  `AK_MEDIA` INT NULL DEFAULT NULL,
  `AK_STATE` TINYINT NOT NULL,
  `AK_REMARK` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`AK_ID`));


-- -----------------------------------------------------
-- Table `Artists_treasure`.`COLLECTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Artists_treasure`.`COLLECTION` ;

CREATE TABLE IF NOT EXISTS `Artists_treasure`.`COLLECTION` (
  `COL_ID` VARCHAR(8) NOT NULL,
  `COL_DATE` DATE NOT NULL,
  `COL_ARTIST` VARCHAR(255) NULL DEFAULT NULL,
  `COL_NAME` VARCHAR(255) NULL DEFAULT NULL,
  `COL_MATERIAL` VARCHAR(255) NULL DEFAULT NULL,
  `COL_SIZE` DECIMAL(6,1) NOT NULL,
  `COL_SIGNATURE_Y` YEAR NOT NULL,
  `COL_SIGNATURE_M` TINYINT NOT NULL,
  `COL_THEME` INT NULL DEFAULT NULL,
  `COL_GET_DATE` DATE NOT NULL,
  `COL_DPRICE` INT NULL DEFAULT NULL,
  `COL_INTRODUCE` TEXT NULL DEFAULT NULL,
  `COL_TIMES` INT NULL DEFAULT NULL,
  `COL_LOCATION` TEXT NOT NULL,
  `COL_MEDIA` VARCHAR(255) NULL DEFAULT NULL,
  `COL_STATE` TINYINT NOT NULL,
  `COL_REMARK` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`COL_ID`));


-- -----------------------------------------------------
-- Table `Artists_treasure`.`THEME`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Artists_treasure`.`THEME` ;

CREATE TABLE IF NOT EXISTS `Artists_treasure`.`THEME` (
  `TE_ID` VARCHAR(7) NOT NULL,
  `TE_NAME` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`TE_ID`));


-- -----------------------------------------------------
-- Table `Artists_treasure`.`PLACE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Artists_treasure`.`PLACE` ;

CREATE TABLE IF NOT EXISTS `Artists_treasure`.`PLACE` (
  `PE_ID` VARCHAR(7) NOT NULL,
  `PE_NAME` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`PE_ID`));


-- -----------------------------------------------------
-- Table `Artists_treasure`.`TRADE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Artists_treasure`.`TRADE` ;

CREATE TABLE IF NOT EXISTS `Artists_treasure`.`TRADE` (
  `TDE_ID` VARCHAR(8) NOT NULL,
  `TDE_PLACE` VARCHAR(255) NOT NULL,
  `TDE_DATE` DATE NOT NULL,
  `TDE_BUYER` VARCHAR(100) NOT NULL,
  `TDE_SELLER` VARCHAR(100) NOT NULL,
  `TDE_TOTAL_ITEM` INT NOT NULL,
  `TDE_TOTAL_PRICE` INT NOT NULL,
  `TDE_REMARK` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`TDE_ID`));


-- -----------------------------------------------------
-- Table `Artists_treasure`.`TRADEDETAIL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Artists_treasure`.`TRADEDETAIL` ;

CREATE TABLE IF NOT EXISTS `Artists_treasure`.`TRADEDETAIL` (
  `TDED_ID` VARCHAR(9) NOT NULL,
  `TDE_ID` VARCHAR(8) NOT NULL,
  `AK_ID` VARCHAR(7) NOT NULL,
  `COL_ID` VARCHAR(8) NOT NULL,
  `TDED_PRICE` INT NOT NULL,
  `TDED_REMARK` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`TDED_ID`),
  INDEX (`TDE_ID` ASC) VISIBLE,
  INDEX (`AK_ID` ASC) VISIBLE,
  INDEX (`COL_ID` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`TDE_ID`)
    REFERENCES `Artists_treasure`.`TRADE` (`TDE_ID`),
  CONSTRAINT ``
    FOREIGN KEY (`AK_ID`)
    REFERENCES `Artists_treasure`.`ARTWORK` (`AK_ID`),
  CONSTRAINT ``
    FOREIGN KEY (`COL_ID`)
    REFERENCES `Artists_treasure`.`COLLECTION` (`COL_ID`));


-- -----------------------------------------------------
-- Table `Artists_treasure`.`EXHIBITION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Artists_treasure`.`EXHIBITION` ;

CREATE TABLE IF NOT EXISTS `Artists_treasure`.`EXHIBITION` (
  `EN_ID` VARCHAR(7) NOT NULL,
  `EN_LOCATION` VARCHAR(255) NOT NULL,
  `EN_ORGANIZER` VARCHAR(255) NOT NULL,
  `EN_NAME` VARCHAR(255) NOT NULL,
  `EN_START` DATE NOT NULL,
  `EN_FINISH` DATE NOT NULL,
  `EN_ITEM` INT NOT NULL,
  `EN_INTRODUCE` TEXT NULL DEFAULT NULL,
  `EN_REMARK` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`EN_ID`));


-- -----------------------------------------------------
-- Table `Artists_treasure`.`EXHIBITIONDETAIL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Artists_treasure`.`EXHIBITIONDETAIL` ;

CREATE TABLE IF NOT EXISTS `Artists_treasure`.`EXHIBITIONDETAIL` (
  `END_ID` VARCHAR(8) NOT NULL,
  `EN_ID` VARCHAR(7) NULL DEFAULT NULL,
  `AK_ID` VARCHAR(7) NULL DEFAULT NULL,
  `COL_ID` VARCHAR(8) NULL DEFAULT NULL,
  `END_NAME` VARCHAR(255) NULL DEFAULT NULL,
  INDEX (`EN_ID` ASC) VISIBLE,
  INDEX (`AK_ID` ASC) VISIBLE,
  INDEX (`COL_ID` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`EN_ID`)
    REFERENCES `Artists_treasure`.`EXHIBITION` (`EN_ID`),
  CONSTRAINT ``
    FOREIGN KEY (`AK_ID`)
    REFERENCES `Artists_treasure`.`ARTWORK` (`AK_ID`),
  CONSTRAINT ``
    FOREIGN KEY (`COL_ID`)
    REFERENCES `Artists_treasure`.`COLLECTION` (`COL_ID`));


-- -----------------------------------------------------
-- Table `Artists_treasure`.`CONTEST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Artists_treasure`.`CONTEST` ;

CREATE TABLE IF NOT EXISTS `Artists_treasure`.`CONTEST` (
  `CT_ID` VARCHAR(7) NOT NULL,
  `CT_LOCATION` VARCHAR(255) NOT NULL,
  `CT_ORGANIZER` VARCHAR(255) NOT NULL,
  `CT_NAME` VARCHAR(255) NOT NULL,
  `CT_START` DATE NOT NULL,
  `CT_END` DATE NOT NULL,
  `CT_ITEM` INT NOT NULL,
  `CT_INTRODUCE` TEXT NOT NULL,
  `CT_REMARK` TEXT NOT NULL,
  PRIMARY KEY (`CT_ID`));


-- -----------------------------------------------------
-- Table `Artists_treasure`.`CONTESTDETAIL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Artists_treasure`.`CONTESTDETAIL` ;

CREATE TABLE IF NOT EXISTS `Artists_treasure`.`CONTESTDETAIL` (
  `CTD_ID` VARCHAR(8) NOT NULL,
  `CT_ID` VARCHAR(7) NOT NULL,
  `AK_ID` VARCHAR(7) NOT NULL,
  `CTD_NAME` VARCHAR(255) NULL DEFAULT NULL,
  `CTD_RANK` INT NOT NULL,
  `CTD_AMOUNT` INT NOT NULL);

USE `Auto_increment` ;

-- -----------------------------------------------------
-- Table `Auto_increment`.`AK_SEQUENCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Auto_increment`.`AK_SEQUENCE` ;

CREATE TABLE IF NOT EXISTS `Auto_increment`.`AK_SEQUENCE` (
  `SEQ` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`SEQ`));


-- -----------------------------------------------------
-- Table `Auto_increment`.`COL_SEQUENCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Auto_increment`.`COL_SEQUENCE` ;

CREATE TABLE IF NOT EXISTS `Auto_increment`.`COL_SEQUENCE` (
  `SEQ` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`SEQ`));


-- -----------------------------------------------------
-- Table `Auto_increment`.`TE_SEQUENCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Auto_increment`.`TE_SEQUENCE` ;

CREATE TABLE IF NOT EXISTS `Auto_increment`.`TE_SEQUENCE` (
  `SEQ` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`SEQ`));


-- -----------------------------------------------------
-- Table `Auto_increment`.`PE_SEQUENCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Auto_increment`.`PE_SEQUENCE` ;

CREATE TABLE IF NOT EXISTS `Auto_increment`.`PE_SEQUENCE` (
  `SEQ` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`SEQ`));


-- -----------------------------------------------------
-- Table `Auto_increment`.`TDE_SEQUENCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Auto_increment`.`TDE_SEQUENCE` ;

CREATE TABLE IF NOT EXISTS `Auto_increment`.`TDE_SEQUENCE` (
  `SEQ` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`SEQ`));


-- -----------------------------------------------------
-- Table `Auto_increment`.`TDED_SEQUENCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Auto_increment`.`TDED_SEQUENCE` ;

CREATE TABLE IF NOT EXISTS `Auto_increment`.`TDED_SEQUENCE` (
  `SEQ` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`SEQ`));


-- -----------------------------------------------------
-- Table `Auto_increment`.`EN_SEQUENCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Auto_increment`.`EN_SEQUENCE` ;

CREATE TABLE IF NOT EXISTS `Auto_increment`.`EN_SEQUENCE` (
  `SEQ` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`SEQ`));


-- -----------------------------------------------------
-- Table `Auto_increment`.`END_SEQUENCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Auto_increment`.`END_SEQUENCE` ;

CREATE TABLE IF NOT EXISTS `Auto_increment`.`END_SEQUENCE` (
  `SEQ` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`SEQ`));


-- -----------------------------------------------------
-- Table `Auto_increment`.`CT_SEQUENCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Auto_increment`.`CT_SEQUENCE` ;

CREATE TABLE IF NOT EXISTS `Auto_increment`.`CT_SEQUENCE` (
  `SEQ` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`SEQ`));


-- -----------------------------------------------------
-- Table `Auto_increment`.`CTD_SEQUENCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Auto_increment`.`CTD_SEQUENCE` ;

CREATE TABLE IF NOT EXISTS `Auto_increment`.`CTD_SEQUENCE` (
  `SEQ` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`SEQ`));


-- -----------------------------------------------------
-- Table `Auto_increment`.`TRADE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Auto_increment`.`TRADE` ;

CREATE TABLE IF NOT EXISTS `Auto_increment`.`TRADE` (
);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
USE `Auto_increment`;

DELIMITER $$

USE `Auto_increment`$$
DROP TRIGGER IF EXISTS `Auto_increment`.`BEFORE_INSERT_TDE_ID` $$
USE `Auto_increment`$$
CREATE TRIGGER BEFORE_INSERT_TDE_ID
BEFORE INSERT ON TRADE
FOR EACH ROW
BEGIN
    DECLARE NEW_ID VARCHAR(8);
    INSERT INTO TDE_SEQUENCE VALUES (NULL);
    SET NEW_ID = CONCAT('TDE', LPAD(LAST_INSERT_ID(), 5, '0'));
    SET NEW.TDE_ID = NEW_ID;
END$$


DELIMITER ;
