DELIMITER //

CREATE TRIGGER AK_DEL_INDEX    
BEFORE DELETE ON ARTWORK
FOR EACH ROW
BEGIN
    DELETE FROM AK_SEQUENCE WHERE SEQ = SUBSTRING(OLD.AK_ID, 4);
END //

CREATE TRIGGER COL_DEL_INDEX    
BEFORE DELETE ON COLLECTION
FOR EACH ROW
BEGIN
    DELETE FROM COL_SEQUENCE WHERE SEQ = SUBSTRING(OLD.COL_ID, 4);
END //

CREATE TRIGGER TE_DEL_INDEX    
BEFORE DELETE ON THEME
FOR EACH ROW
BEGIN
    DELETE FROM TE_SEQUENCE WHERE SEQ = SUBSTRING(OLD.TE_ID, 4);
END //


DELIMITER ;
